config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount MissionControl::Jobs::Engine, at: "/jobs"
  mount SolidErrors::Engine, at: "/solid_errors"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", :as => :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", :as => :pwa_manifest

  # Defines the root path route ("/")
  root "start_page#index", as: :start

  namespace :oauth do
    get "/login", to: "sessions#login", as: "login"
    get "/callback", to: "sessions#callback"
  end

  namespace :party_data do
    scope "/:code" do
      scope "/settings" do
        get "/device_list", to: "settings#device_list", as: "party_device_list"
        post "/party_device", to: "settings#party_device", as: "set_party_device"
      end
      scope "/queue" do
        post "/add", to: "queues#add_song_to_queue", as: "add_to_queue"
      end
      get "/search", to: "search#search", as: "search"
    end
  end

  scope "/party" do
    post "/start/:code", to: "parties#start", as: "start_party"
    post "/stop/:code", to: "parties#stop", as: "stop_party"
    post "/skip/:code", to: "parties#skip", as: "skip_party"
    post "/resume/:code", to: "parties#resume", as: "resume_party"
    get "/:code/select_device", to: "parties#select_device", as: "select_device"
    get "/settings/:code", to: "parties#settings", as: "party_settings"
    get "/join/:code", to: "parties#join", as: "join_party"
    post "/create", to: "parties#create", as: "create_party"
    post "/:code/end", to: "parties#end", as: "end_party"
    get "/list", to: "parties#index", as: "party_list"
    get "/:code", to: "parties#show", as: "show_party"
  end
  
  scope '/accounts' do
    get '', to: "accounts#index", as: "account_settings"
    post '/destroy', to: "accounts#destroy", as: "account_destroy"
    post '/logout', to: "accounts#logout", as: "logout"
  end
  
  get '/terms_and_conditions', to: "legal#terms_and_conditions", as: "terms_and_conditions"
  get '/privacy_policy', to: "legal#privacy_policy", as: "privacy_policy"
  get '/cookie_policy', to: "legal#cookie_policy", as: "cookie_policy"
  resources :temporal_sessions, only: [ :create, :destroy ]

  get "/home", to: "home#index"

  match "*unmatched", to: "application#not_found_method", via: :all
end

app/models/party.rb
# frozen_string_literal: true

class Party < ApplicationRecord
  MAX_DURATION = 6.hours

  belongs_to :user

  has_many :party_songs, dependent: :destroy
  has_many :songs, through: :party_songs
  has_many :party_users, dependent: :destroy
  has_many :temporal_users, through: :party_users, source: :user, source_type: "TemporalUser"
  has_many :users, through: :party_users, source: :user, source_type: "User"

  validates :name, presence: true, uniqueness: { scope: :user_id }, length: { in: 1..15 }
  validates :code, presence: true, uniqueness: true, length: { is: 6 }

  def currently_playing_song
    party_songs.where(is_playing: true).first&.song
  end

  def currently_playing_party_song
    party_songs.where(is_playing: true).first
  end

  def non_played_songs
    songs.where(party_songs: { played: false })
  end
  
  def next_party_song
    party_songs.where(next_song: true).first || non_played_songs.first
  end

  def has_pending_songs?
    non_played_songs.count > 0
  end

  def queue_count
    non_played_songs.count
  end

  def ended?
    self.ended_at != nil
  end
  
  def end
    self.update(ended_at: Time.now) unless ended?
  end
end

app/controllers/parties_controller.rb
# frozen_string_literal: true

class PartiesController < ApplicationController
  before_action :authorize, except: [ :index, :join, :show ]
  before_action :party_exists?, except: [ :index, :create ]
  before_action :party_has_device?, except: [ :create, :settings, :select_device, :index ]
  before_action :user_in_party?, only: :show
  before_action :user_owns_party?, only: [ :settings, :select_device, :start, :end, :resume, :stop, :skip ]
  before_action :user_is_premium?, only: :create
  before_action :owner_is_premium?, only: [ :join, :show ]

  rate_limit to: 7, within: 3.minutes,
    by: -> { request.remote_ip },
    with: -> { rate_limit_exceeded },
    only: [ :create, :join ]

  # TODO: what happens if user is premium but changes to free?
  class RetriesDepleted < StandardError; end
  class PartyAlreadyExists < StandardError; end
  class RateLimitExceeded < StandardError
    def initialize(remote_ip)
      super("Rate Limit Exceeded - remote_ip: #{remote_ip}")
    end
  end

  PARTY_CREATION_RETRIES = 3

  def create
    party = create_party_with_random_code

    party.users << current_user

    redirect_to select_device_path(code: party.code)
  rescue RetriesDepleted,
    PartyAlreadyExists => e

    report_error(e)
    if e.class == PartyAlreadyExists
      flash[:error] = "You already have a party with that name"
    else
      flash[:error] = "There was an error creating the party"
    end
    redirect_to home_path
  end

  def join
    if logged_with_spotify?
      session[:temporal_session] = nil
      party.users << current_user
      flash[:notice] = "Party joined!"
      redirect_to show_party_path(code: code)
    elsif session[:temporal_session].present?
      redirect_to show_party_path(code: code)
    else
      session[:joining_party_code] = code
      @code = code
      render "non_logged_join"
    end
  rescue ActiveRecord::RecordInvalid,
    ActiveRecord::RecordNotUnique => e
    report_error(e)
    flash[:notice] = "You have already joined!"
    redirect_to show_party_path(code: code)
  end

  def show
    @user_is_owner = current_user == party.user
    @party_songs = party.party_songs.includes(:song).where(played: false).load
  end

  def start
    Spotify::Api::Playback::TransferPlaybackService.new(party.user.access_token, party.device_id, play: false).call
    party_song_to_play = party.next_party_song

    PlaySongAndEnqueueNextService.new(party_song: party_song_to_play, party: party).call
    PartyStatusUpdaterJob.set(wait: 3.seconds).perform_later(party_id: party.id)

    party.update(started: true)
    UpdateCurrentlyPlayingService.new(party: party).call
    head :ok
  rescue Spotify::ApiError => e
    report_error(e)
    head 500
  end

  def stop
    Spotify::Api::Playback::TransferPlaybackService.new(party.user.access_token, party.device_id, play: false).call

    Spotify::Api::Playback::StopService.new(party.user.access_token, party.device_id).call
    party.update(stopped: true)
    UpdateCurrentlyPlayingService.new(party: party).call
    head :ok
  rescue Spotify::ApiError => e
    report_error(e)
    head 500
  end
  
  def skip
    next_song_job = SolidQueue::Job.find_by(id: party.next_song_job_id)
    next_song_job.destroy if next_song_job.present?
    
    PlayNextSongJob.perform_now(current_party_song: party.currently_playing_party_song)
    
    head :ok
  rescue Spotify::ApiError => e
    report_error(e)
    head 500
  end

  def resume
    Spotify::Api::Playback::TransferPlaybackService.new(party.user.access_token, party.device_id, play: false).call
    next_party_song = party.next_party_song

    if party.currently_playing_song
      Spotify::Api::Playback::StartService.new(party.user.access_token, party.device_id).call
    elsif next_party_song.present?
      PlaySongAndEnqueueNextService.new(party_song: next_party_song, party: party).call
    end
    party.update(stopped: false)

    UpdateCurrentlyPlayingService.new(party: party).call
    head :ok
  rescue Spotify::ApiError => e
    report_error(e)
    head 500
  end

  def settings
    @devices = Spotify::Api::Playback::AvailableDevicesService.new(current_user.access_token).call
    @devices = @devices["devices"]&.map { |device| DevicePresenter.new(device) }
  end

  def select_device
    if party.device_id.present?
      redirect_to home_path
    else
      @devices = Spotify::Api::Playback::AvailableDevicesService.new(current_user.access_token).call
      @devices = @devices["devices"]&.map { |device| DevicePresenter.new(device) }
    end
  rescue Spotify::ApiError => e
    report_error(e)
    flash[:error] = "There was an error, try again"
    redirect_to home_path
  end

  def index
    temporal_user = TemporalUser.find_by(id: session[:temporal_session])
    if current_user
      @currently_joined = current_user.joined_parties.where.not(user_id: current_user.id).where(ended_at: nil)
      @my_parties = current_user.parties.where(ended_at: nil)
    elsif temporal_user
      @currently_joined = temporal_user.party
      render 'temporal_user_party_index'
    else
      flash[:error] = "Join a party or create an account to access that option"
      redirect_to start_path
    end
  end

  def end
    party.update(ended_at: Time.now)
    flash[:notice] = "Party ended!"
    redirect_back(fallback_location: home_path)
  end

  private

  def create_party_with_random_code
    retries = 0
    random_code = nil
    party = nil

    loop do
      raise RetriesDepleted if retries >= PARTY_CREATION_RETRIES
      random_code = SecureRandom.hex(3)

      party = Party.create(user: current_user, name: name, code: random_code, ends_at: Time.now + Party::MAX_DURATION)

      raise PartyAlreadyExists if party.errors[:name].present?

      break if party.valid?

      retries += 1
    end

    PartyEnderJob.set(wait_until: party.ends_at).perform_later(party.id)
    party
  end

  def party_exists?
    if party.nil? || party.ended?
      flash[:error] = "That party does not exist"

      redirect_to(start_path)
      return
    end

    true
  end

  def party_has_device?
    if party.device_id.nil?
      if party.user_id == current_user&.id
        flash[:error] = "You have to add a device to the party"
        redirect_to select_device_path(code: code)
      else
        flash[:error] = "The party is being created. Try again"
        redirect_back(fallback_location: start_path)
      end
    end
  end

  def user_owns_party?
    redirect_to show_party_path(code: code) unless party.user_id == current_user&.id
  end

  def user_in_party?
    # TODO:maybe this query can be optimized
    if current_user
      user = current_user
    elsif session[:temporal_session].present?
      user = TemporalUser.find_by(id: session[:temporal_session])
    else
      user = nil
    end

    return true if user.present? && party.party_users.exists?(user: user)

    session[:temporal_session] = nil
    flash[:error] = "You have to join the party first"
    redirect_to join_party_path(code: code)
  end

  def rate_limit_exceeded
    report_error(RateLimitExceeded.new(request.remote_ip))
    flash[:error] = "Too many party creation requests. Please wait some minutes"
    redirect_to home_path
  end

  def user_is_premium?
    unless current_user.is_premium?
      flash[:error] = 'You need a premium Spotify account to create a party'
      redirect_to home_path
    end
  end

  def owner_is_premium?
    unless party.user.is_premium?
      flash[:error] = 'The party owner needs a premium Spotify account'
      redirect_to home_path
    end
  end

  def code
    @code ||= params.require(:code)
  end

  def party
    @party ||= Party.find_by(code: code)
  end

  def name
    @name ||= params.require(:name)
  end
end

app/views/parties/_currently_playing.html.erb
<% if party.has_pending_songs? && !party.started? %>
    <% if user_is_owner %>
    <%= render partial: "party_songs/start_button", locals: { party: party} %>
    <% else %>
    <div id="currently_playing" class="flex h-full w-full items-center justify-center">
        <p class="animate-pulse text-spotify-green font-bold text-xl">Wait for the creator to start the party</p>
    </div>
    <% end %>
<% elsif (party.currently_playing_song || party.has_pending_songs?) && party.stopped? %>
    <% if user_is_owner %>
    <div id="currently_playing" class="flex h-full w-full items-center justify-center">
        <button data-action="click->party#resume" data-resume-url="<%= resume_party_path(code: party.code) %>"class="flex items-center bg-gray-200 text-black font-extrabold p-2 h-3/5 rounded-xl hover:bg-spotify-gray-clear hover:border-spotify-green hover:text-spotify-green">
           <%= image_tag 'dark-play-button-icon.svg', class: 'w-8 h-8' %><span class="text-xl">Resume</span>
        </button>
    </div>
    <% else %>
    <div id="currently_playing" class="flex h-full w-full items-center justify-center">
        <p class="animate-pulse text-spotify-green font-bold text-xl">Wait for the creator to start the party</p>
    </div>
    <% end %>
<% elsif party.started? && !party.stopped?%>
    <%= render partial: "party_songs/currently_playing", locals: { song: party.currently_playing_song, user_is_owner: user_is_owner, party: party } %>
<% else %>
    <div id="currently_playing" class="flex h-full w-full items-center justify-center">
        <p class="animate-pulse text-spotify-green font-bold text-2xl">Add a song to start</p>
    </div>
<% end %>

app/views/parties/_device_list.html.erb
<% if devices.empty? %>
<div class="flex flex-col h-full w-full justify-center items-center gap-2">
    <div class="animate-spin rounded-full h-16 w-16 border-2 border-t-8 border-zinc-400"></div>
    <span class="flex gap-1 font-medium text-center">Searching your <%= image_tag 'spotify-full-logo.svg', class: 'w-[70px]' %> devices</span>
</div>
<% else %>
<div class="grid grid-cols-2 <%= 'lg:grid-cols-3' if devices.count > 2 %> gap-4 w-full h-full max-h-screen p-4 overflow-y-auto overflow-hidden custom-scrollbar">
    <% devices.each do |device| %>
        <div data-device-id="<%= device.id %>" class="flex flex-col justify-center items-center gap-2 bg-spotify-gray-secondary hover:bg-spotify-gray-highlight w-full aspect-square relative" data-action="click->select-device#selectDevice">
            <p class="text-white text-5xl"><%= device.icon %></p>
            <p class="text-white text-xl lg:text-2xl text-center break-words px-4"><%= device.name %></p>
        </div>
    <% end %>
    <div class="flex flex-col aspect-square w-full justify-center items-center gap-2">
        <div class="animate-spin rounded-full h-16 w-16 border-2 border-t-8 border-zinc-400"></div>
        <span class="font-medium text-center">Searching for devices</span>
    </div>
</div>
<% end %>

app/views/parties/_party_banner.html.erb
<div class="flex items-center rounded-2xl justify-between p-2 bg-spotify-gray-clear w-full h-24">
    <h1 class="text-2xl font-bold mx-4 truncate max-w-40"><%= party.name.capitalize %> </h1>
    <div data-controller="invite">
      <div class="flex flex-col lg:flex-row items-center invite-container">
        <button data-controller="party" data-party-target="copyButton" data-action="click->party#copy" data-invite-url="<%= join_party_url(code: @party.code)%>" 
            class="bg-spotify-gray-clear text-gray-300 hover:bg-spotify-gray-highlight rounded-lg py-2 px-2.5 gap-1 inline-flex items-center justify-center border-spotify-gray-highlight border">
                <%= image_tag 'share-icon.svg', class: 'w-5 h-5' %>
            <span data-party-target="copyButtonText" class="text-xs font-semibold">Invite</span>
        </button>
      </div>
    </div>
    <% if @user_is_owner %>
    <%= link_to party_settings_path(code: party.code ), class: "font-semibold text-lg mx-4 " do %>
        <%= image_tag 'party-settings-icon.svg', class: 'w-8 h-8' %>
    <% end %>
    <% end %>
</div>

app/views/parties/_party_preview.html.erb
<div class="flex items-center justify-between p-4 hover:bg-spotify-gray-highlight">
    <span class="text-xl font-semibold truncate"><%=party.name%></span>
    <div class="flex gap-3">
    <% if owner %>
        <%= button_to 'End', end_party_path(code: party.code), method: :post, class: "font-bold bg-red-500 px-2.5 py-1.5 rounded" %>
    <% end %>
    <%= link_to 'Join', show_party_path(code: party.code), method: :post, class: "font-bold bg-spotify-green px-2.5 py-1.5 rounded" %>
    </div>
</div>

app/views/parties/_song_queue.html.erb
<div class="flex flex-col gap-2 p-2 rounded-2xl overflow-y-auto bg-spotify-gray-clear w-full h-full custom-scrollbar">
    <h2 class="ml-2 mt-1 text-xl md:text-2xl font-bold">Next songs</h2>
    <ul id="party_songs_list" class="flex flex-col w-full h-full p-3 pt-4 gap-5 overflow-y-auto rounded-2xl bg-spotify-gray-dark custom-scrollbar">
        <% party_songs.each_with_index do |party_song| %>
          <%= render partial: "party_songs/party_song", locals: { song: party_song.song, party_song_id: party_song.id } %>
        <% end %>
    </ul>    
</div>

app/views/parties/index.html.erb
<div class="flex flex-col w-full h-full p-4 rounded-2xl gap-2 bg-spotify-gray-clear">
    <p class="text-xl sticky top-0 bg-spotify-gray-clear font-semibold">Your ongoing parties</p>
    <div class="flex flex-col h-1/2 overflow-y-auto custom-scrollbar">
      <% @my_parties.each do |party| %>
          <%= render partial: 'party_preview', locals: { party: party, owner: true }%>
      <% end %>
    </div>
    <hr class="border-t border-spotify-gray-highlight opacity-30">
    <p class="text-xl sticky top-0 bg-spotify-gray-clear font-semibold">Ongoing joined parties</p>
    <div class="h-1/2 overflow-y-auto custom-scrollbar">
        <% @currently_joined.each do |party| %>
            <%= render partial: 'party_preview', locals: { party: party, owner: false }%>
        <% end %>
    </div>
</div>

app/views/parties/non_logged_join.html.erb
<div class="flex flex-col justify-center h-full rounded-xl bg-black items-center gap-4">
    <div class="flex flex-col justify-center gap-4 items-center">
        <%= render 'shared/join_without_account' %>
        <div class="relative flex py-5 items-center w-full">
            <div class="flex-grow border-t border-gray-400"></div>
            <span class="flex-shrink mx-2 text-gray-400 px-4 font-bold text-xl">or</span>
            <div class="flex-grow border-t border-gray-400"></div>
        </div>
        <%= render partial: 'shared/login_with_spotify', locals: { text: "Join with Spotify"} %>
    </div>
</div>

    

app/views/parties/select_device.html.erb
<div data-controller="select-device" data-device-set-url="<%= party_data_set_party_device_path(code: @party.code)%>"  data-device-fetch-url="<%= party_data_party_device_list_path(code: @party.code)%>" class="flex flex-col h-full justify-between items-center">
    <div class="flex flex-col flex-grow items-center justify-center">
        <h1 class="text-4xl font-bold whitespace-normal break-words">Select a device</h1>
        <p class="text-lg text-gray-400  text-center">
            To reproduce the music
        </p>
    </div>
    <span class="flex flex-col justify-start md:justify-center ml-2 text-md text-gray-500 text-left whitespace-normal self-start break-words">
        <span class="text-gray-400 font-semibold">🔎 Don't see your device?</span> 
        <span class="flex items-center gap-2">
          1. Open 
          <%= image_tag 'spotify-full-logo.svg', class: 'w-[80px]' %> 
        </span>
        <span class="">2. Your device should appear here soon</span> 
    </span>
    <div data-select-device-target="devicesGrid" class="h-3/4 md:h-5/6">
        <%= render partial: 'parties/device_list', locals: { devices: @devices } %>
    </div>
    <div class="animate-spin hidden rounded-full h-14 w-14 border-2 border-t-8 border-zinc-400 absolute bottom-20 z-50 place-self-center items-center" data-select-device-target="spinner"></div>
    <p data-select-device-target="setDeviceButton"
       data-action="click->select-device#setDevice"
       class="hidden absolute bottom-20 z-50 px-6 py-4 rounded-lg w-auto place-self-center bg-spotify-green items-center font-bold text-xl hover:bg-green-700 hover:cursor-pointer"
       >
           Use this device
       </p>
</div>

app/views/parties/settings.html.erb
<div data-controller="select-device" data-device-set-url="<%= party_data_set_party_device_path(code: @party.code)%>"  data-device-fetch-url="<%= party_data_party_device_list_path(code: @party.code)%>" class="flex flex-col h-full justify-between items-center">
    <div class="flex flex-col flex-grow justify-between my-2 items-center">
        <div class="flex flex-col items-center justify-center">
            <h1 class="text-4xl font-bold whitespace-normal break-words">Change the party device</h1>
        </div>
        <p class="text-md text-gray-600 text-left whitespace-normal break-words">
            🔎 <span class="text-gray-500 font-semibold">Dont see your device?</span> Open the Spotify app and your device should appear soon
        </p>
    </div>
    <div data-select-device-target="devicesGrid" class="h-3/4 md:h-full">
        <%= render partial: 'parties/device_list', locals: { devices: @devices } %>
    </div>
    <div class="animate-spin hidden rounded-full h-14 w-14 border-2 border-t-8 border-zinc-400 absolute bottom-20 z-50 place-self-center items-center" data-select-device-target="spinner"></div>
    <p data-select-device-target="setDeviceButton"
       data-action="click->select-device#setDevice"
       class="hidden absolute bottom-20 z-50 p-4 rounded-2xl w-auto place-self-center bg-spotify-green items-center font-semibold text-xl hover:bg-green-700 hover:cursor-pointer"
       >
           Use this device
       </p>
</div>

app/views/parties/show.html.erb
<% if @user_is_owner %>
<%= turbo_stream_from "party_#{@party.code}_owner" %>    
<% else %>
<%= turbo_stream_from "party_#{@party.code}_guest" %>
<% end %>
<div class="flex flex-col h-full gap-2">
    <div class="flex flex-col gap-2 h-[calc(100%-80px)] md:h-[calc(100%-96px)] overflow-hidden">
        <!-- First child div -->
        <div class="relative flex flex-col px-2 py-1 rounded-2xl bg-spotify-gray-clear w-full h-fit z-10">
            <div data-search-url="<%= party_data_search_path(code: @party.code)%>" data-controller="search" class="relative">
                <div class="flex justify-center h-14 bg-spotify-gray-clear items-center">
                    <input data-search-target="searchInput" data-action="click->search#open input->search#checkInput" class="bg-spotify-gray-dark rounded-3xl w-full focus:outline-none focus:border-spotify-green focus:ring-spotify-green" placeholder="Search a song">
                    </input>
                </div>
                <div data-search-target="searchResults" class="hidden flex flex-col absolute top-14 w-full bg-opacity-90 rounded-xl p-2 overflow-y-auto h-72 bg-black custom-scrollbar">
                </div>
            </div>
        </div>
        
        <!-- Second child div with flex-grow -->
        <div class="flex flex-col w-full gap-2 flex-grow overflow-y-auto">
            <%= render partial: "parties/party_banner", locals: { party: @party} %>
            <%= render partial: "parties/song_queue", locals: { party_songs: @party_songs} %>
        </div>
    </div>
    <div data-controller="party" class="p-2 bg-black rounded-2xl w-full md:h-24 h-20">
        <div class="flex hidden justify-center items-center" data-party-target="spinner">
            <div class="animate-spin rounded-full h-14 w-14 border-2 border-t-8 border-zinc-400"></div>
        </div>
        <div class="flex hidden justify-center items-center" data-party-target="spotifyError">
            <span class="p-2 rounded-2xl w-fit bg-red-500 items-center font-semibold text-md lg:text-lg break-words whitespace-normal">We couldnt connect to your device. Open your Spotify app and try again</span>
        </div>        
        <%= render partial: "parties/currently_playing", locals: { party: @party, user_is_owner: @user_is_owner} %>
    </div>
</div>

app/views/parties/temporal_user_party_index.html.erb
<div class="flex flex-col w-full h-full p-4 rounded-2xl gap-2 bg-spotify-gray-clear">
    <div class="flex flex-col justify-center items-center h-1/2">
      <%= render 'shared/login_with_spotify'%>
    </div>
    <hr class="border-t border-spotify-gray-highlight opacity-30">
    <p class="text-xl sticky top-0 bg-spotify-gray-clear font-semibold">Ongoing joined parties</p>
    <div class="h-1/2 overflow-y-auto custom-scrollbar">
        <%= render partial: 'party_preview', locals: { party: @currently_joined, owner: false }%>
    </div>
</div>