config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount MissionControl::Jobs::Engine, at: "/jobs"
  mount SolidErrors::Engine, at: "/solid_errors"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", :as => :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", :as => :pwa_manifest

  # Defines the root path route ("/")
  root "start_page#index", as: :start

  namespace :oauth do
    get "/login", to: "sessions#login", as: "login"
    get "/callback", to: "sessions#callback"
  end

  namespace :party_data do
    scope "/:code" do
      scope "/settings" do
        get "/device_list", to: "settings#device_list", as: "party_device_list"
        post "/party_device", to: "settings#party_device", as: "set_party_device"
      end
      scope "/queue" do
        post "/add", to: "queues#add_song_to_queue", as: "add_to_queue"
      end
      get "/search", to: "search#search", as: "search"
    end
  end

  scope "/party" do
    post "/start/:code", to: "parties#start", as: "start_party"
    post "/stop/:code", to: "parties#stop", as: "stop_party"
    post "/skip/:code", to: "parties#skip", as: "skip_party"
    post "/resume/:code", to: "parties#resume", as: "resume_party"
    get "/:code/select_device", to: "parties#select_device", as: "select_device"
    get "/settings/:code", to: "parties#settings", as: "party_settings"
    get "/join/:code", to: "parties#join", as: "join_party"
    post "/create", to: "parties#create", as: "create_party"
    post "/:code/end", to: "parties#end", as: "end_party"
    get "/list", to: "parties#index", as: "party_list"
    get "/:code", to: "parties#show", as: "show_party"
  end
  
  scope '/accounts' do
    get '', to: "accounts#index", as: "account_settings"
    post '/destroy', to: "accounts#destroy", as: "account_destroy"
    post '/logout', to: "accounts#logout", as: "logout"
  end
  
  get '/terms_and_conditions', to: "legal#terms_and_conditions", as: "terms_and_conditions"
  get '/privacy_policy', to: "legal#privacy_policy", as: "privacy_policy"
  get '/cookie_policy', to: "legal#cookie_policy", as: "cookie_policy"
  resources :temporal_sessions, only: [ :create, :destroy ]

  get "/home", to: "home#index"

  match "*unmatched", to: "application#not_found_method", via: :all
end

app/views/shared/_create_party.html.erb
<div data-controller="create-party">
<%= form_with url: create_party_path, method: :post, class: "relative flex flex-col justify-center items-center rounded-lg w-80 gap-3" do |form| %>
    <%= form.text_field :name, 
        placeholder: "Party name", maxlength: 15, minlength: 1, required: true, 
        class: "bg-black text-gray-200 text-center text-3xl w-full border border-gray-400 hover:border-black focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent font-bold py-3 px-5 rounded", 
        data: { create_party_target: "name" } %>
    <p data-create-party-target="nameError" class="hidden text-xs font font-semibold text-red-500"></p>
    <%= form.submit "Create a party", 
        class: "py-2 w-full rounded font-extrabold text-xl text-center bg-spotify-green hover:bg-green-700", 
        data: { action: 'click->create-party#validate' } %>
<% end %>
</div>

app/views/shared/_join_party.html.erb
<div data-controller="join-party" class="flex flex-col justify-center items-center rounded-lg w-80 gap-3">
    <input maxlength="6" minlength="6" placeholder="Code" data-join-party-target="code" class="bg-black text-gray-200 text-center text-3xl w-full border border-gray-400 hover:border-black focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent font-bold py-3 px-5 rounded">
    <p data-join-party-target="codeError" class="hidden text-xs font font-semibold text-red-500"></p>
    <button data-action="click->join-party#join" class="py-2 w-full rounded font-extrabold text-xl text-center bg-spotify-green hover:bg-green-700">Join party</button>
</div>

app/views/shared/_join_without_account.html.erb
<div data-controller="join-party" data-join-party-party-code-value="<%= @code %>" data-join-party-party-show-url-value="<%= show_party_path %>" data-join-party-temporal-session-create-value="<%= temporal_sessions_path %>" class="flex flex-col justify-center items-center rounded-lg w-80 gap-3">
    <input maxlength="13" placeholder="Name" data-join-party-target="name" class="bg-black text-gray-200 text-center text-3xl w-full border border-gray-400 hover:border-black focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent font-bold py-3 px-5 rounded">
    <p data-join-party-target="nameError" class="hidden text-xs font font-semibold text-red-500"></p>
    <button data-action="click->join-party#non_oauth_join" class="py-2 w-full rounded font-extrabold text-xl text-center bg-spotify-green hover:bg-green-700">Join without an account</button>
</div>

app/views/shared/_login_with_spotify.html.erb
<div class="relative w-fit">
    <div class="absolute -inset-1 opacity-85 bg-gradient-to-br from-spotify-green blur to-purple-600 rounded animate-tilt"></div>
    <div class="relative flex flex-col justify-center items-center w-80 gap-3">
        <%= link_to oauth_login_path, class: 'flex bg-black items-center justify-center text-lg w-full border-gray-400 hover:bg-spotify-gray-clear font-semibold py-3 px-5 rounded' do %>
        <%= image_tag 'spotify-icon.svg', class: 'w-7 mr-2' %>
        <%= defined?(text) ? text : "Create a party with Spotify" %>
        <% end %>
    </div>
</div>
<span class="text-xs text-slate-400 w-80">
    By logging in with Spotify, you accept our 
    <a href="<%= terms_and_conditions_path %>" class="underline font-bold">Terms and Conditions</a>
    , our <a href="<%= privacy_policy_path %>" class="font-bold underline">Privacy Policy</a> 
    and our <a href="<%= cookie_policy_path %>" class="underline font-bold">Cookie Policy</a>.
</span>

app/views/shared/_need_login.html.erb
<div class="flex flex-col w-full h-full justify-center items-center gap-6 bg-black rounded-xl">
    <h1 class="text-xl font-semibold">To access this functionality</h1>
    <%= render partial: 'shared/login_with_spotify', locals: { text: "Join with Spotify"} %>
</div>

app/views/shared/_user_actions.html.erb
<%= render 'shared/join_party' %>
<div class="relative flex py-5 items-center w-full">
    <div class="flex-grow border-t border-gray-400"></div>
    <span class="flex-shrink mx-2 text-gray-400 px-4 font-bold text-xl">or</span>
    <div class="flex-grow border-t border-gray-400"></div>
</div>
<% if !!logged_with_spotify? %>
    <%= render 'shared/create_party' %>
<% else %>
    <%= render 'shared/login_with_spotify' %>
<% end %>