config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount MissionControl::Jobs::Engine, at: "/jobs"
  mount SolidErrors::Engine, at: "/solid_errors"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", :as => :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", :as => :pwa_manifest

  # Defines the root path route ("/")
  root "start_page#index", as: :start

  namespace :oauth do
    get "/login", to: "sessions#login", as: "login"
    get "/callback", to: "sessions#callback"
  end

  namespace :party_data do
    scope "/:code" do
      scope "/settings" do
        get "/device_list", to: "settings#device_list", as: "party_device_list"
        post "/party_device", to: "settings#party_device", as: "set_party_device"
      end
      scope "/queue" do
        post "/add", to: "queues#add_song_to_queue", as: "add_to_queue"
      end
      get "/search", to: "search#search", as: "search"
    end
  end

  scope "/party" do
    post "/start/:code", to: "parties#start", as: "start_party"
    post "/stop/:code", to: "parties#stop", as: "stop_party"
    post "/skip/:code", to: "parties#skip", as: "skip_party"
    post "/resume/:code", to: "parties#resume", as: "resume_party"
    get "/:code/select_device", to: "parties#select_device", as: "select_device"
    get "/settings/:code", to: "parties#settings", as: "party_settings"
    get "/join/:code", to: "parties#join", as: "join_party"
    post "/create", to: "parties#create", as: "create_party"
    post "/:code/end", to: "parties#end", as: "end_party"
    get "/list", to: "parties#index", as: "party_list"
    get "/:code", to: "parties#show", as: "show_party"
  end
  
  scope '/accounts' do
    get '', to: "accounts#index", as: "account_settings"
    post '/destroy', to: "accounts#destroy", as: "account_destroy"
    post '/logout', to: "accounts#logout", as: "logout"
  end
  
  get '/terms_and_conditions', to: "legal#terms_and_conditions", as: "terms_and_conditions"
  get '/privacy_policy', to: "legal#privacy_policy", as: "privacy_policy"
  get '/cookie_policy', to: "legal#cookie_policy", as: "cookie_policy"
  resources :temporal_sessions, only: [ :create, :destroy ]

  get "/home", to: "home#index"

  match "*unmatched", to: "application#not_found_method", via: :all
end

app/models/party_song.rb
# frozen_string_literal: true

class PartySong < ApplicationRecord
  belongs_to :song
  belongs_to :party

  validates :position, uniqueness: { scope: :party_id }
  
  after_create_commit :broadcast_queue_change

  ADD_TO_QUEUE_RETRIES = 3

  def self.add_song_to_queue(party_id:, song_id:)
    retries ||= 0
    max_position = PartySong.where(party_id: party_id).maximum(:position) || 0
    is_first_song = PartySong.where(party_id: party_id, played: false).count == 0
    PartySong.create!(party_id: party_id, song_id: song_id, position: max_position + 1, next_song: is_first_song)
  rescue ActiveRecord::RecordInvalid => e
    if e.record.errors.details[:position].any? { |error| error[:error] == :taken } && retries < ADD_TO_QUEUE_RETRIES
      retries += 1

      retry
    else
      raise e
    end
  end

  private

  def broadcast_queue_change
    unless self.is_playing
      broadcast_append_later_to "party_#{party.code}_guest", target: "party_songs_list", locals: { song: song, party_song_id: self.id }
      broadcast_append_later_to "party_#{party.code}_owner", target: "party_songs_list", locals: { song: song, party_song_id: self.id }
    end

    if party.queue_count == 1
      UpdateCurrentlyPlayingService.new(party: party).call
    end
  end
end

app/views/party_songs/_currently_playing.html.erb
<div id="currently_playing" class="relative flex h-full items-center justify-between">
    <div class="flex items-center gap-2  min-w-0">
        <img src="<%= song.image %>" class="w-14 h-14 rounded-sm lg:rounded">
        <div class="flex flex-col gap-1 my-2 overflow-hidden">
          <div class="overflow-hidden text-ellipsis whitespace-nowrap">
            <p class="font-semibold text-base truncate"><%= song.name %></p>
              <p class="font-semibold text-gray-500 text-xs truncate"><%= song.artists.join(',') %></p>
          </div>
          <%= link_to "http://open.spotify.com/track/#{song.spotify_song_id}", target: '_blank', class: 'inline-block flex items-center gap-2' do %>
            <span class='text-xs font-semibold text-gray-300 underline'>LISTEN ON</span> <%= image_tag('spotify-full-logo.svg', class: 'w-[75px] md:w-[90px]') %>
          <% end %>
        </div>
    </div>
    
    <% if user_is_owner %>
    <div class="flex items-center h-full bg-blackZ gap-2">
        <div data-action="click->party#stop" data-stop-url="<%= stop_party_path(code: party.code)%>" class="flex items-center bg-gray-200 text-black font-extrabold p-2 h-3/5 rounded-xl hover:bg-spotify-gray-clear hover:border-spotify-green hover:text-spotify-green">
            Stop
        </div>
        <div data-action="click->party#skip" data-skip-url="<%= skip_party_path(code: party.code)%>" class="flex items-center bg-gray-200 text-black font-extrabold p-2 h-3/5 rounded-xl hover:bg-spotify-gray-clear hover:border-spotify-green hover:text-spotify-green">
            Skip
        </div>
    </div>
    <% else %>
    <div class="flex w-32 bg-black h-full items-center">
        <%= image_tag 'play-button-icon.svg', class: 'w-9 h-9' %> 
        <p class="animate-pulse font-bold">Playing</p>
    </div>
    <% end %>
</div>

app/views/party_songs/_party_song.html.erb
<li id="<%="party_song_#{party_song_id}"%>" class="flex items-center gap-1 justify-between h-14">
    <div id="<%= song.spotify_song_id %>" class="flex items-center gap-2 flex-grow min-w-0">
        <img src="<%= song.image %>" class="w-16 rounded-sm lg:rounded">
        <div class="flex flex-col gap-1 my-2 overflow-hidden">
          <div class="overflow-hidden text-ellipsis whitespace-nowrap">
            <p class="font-semibold text-base truncate"><%= song.name %></p>
              <p class="font-semibold text-gray-500 text-xs truncate"><%= song.artists.join(',') %></p>
          </div>
          <%= link_to "http://open.spotify.com/track/#{song.spotify_song_id}", target: '_blank', class: 'inline-block flex items-center gap-2' do %>
            <span class='text-xs font-semibold text-gray-300 underline'>LISTEN ON</span> <%= image_tag('spotify-full-logo.svg', class: 'w-[75px] md:w-[90px]') %>
          <% end %>
        </div>
    </div>
    <% if false %>
    <div class="flex items-center bg-gray-200 text-black font-extrabold p-2 h-3/5 rounded-xl hover:bg-spotify-gray-clear hover:border-spotify-green hover:text-spotify-green">
    <%= image_tag 'dark-heart-icon.svg', class: 'w-5 h-5' %>
    </div>
    <div class="flex items-center bg-gray-200 text-black font-extrabold p-2 h-3/5 rounded-xl hover:bg-spotify-gray-clear hover:border-spotify-green hover:text-spotify-green">
        <%= image_tag 'dark-trash-icon.svg', class: 'w-5 h-5' %>
    </div>
    <% end %>
</li>

app/views/party_songs/_start_button.html.erb
<div id="currently_playing" class="flex h-full w-full items-center justify-center">
    <button data-action="click->party#start" data-start-url="<%= start_party_path(code: party.code)%>"class="flex items-center bg-gray-200 text-black font-extrabold p-2 h-3/5 rounded-xl hover:bg-spotify-gray-clear hover:border-spotify-green hover:text-spotify-green">
        Start the party!
    </button>
</div>