config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount MissionControl::Jobs::Engine, at: "/jobs"
  mount SolidErrors::Engine, at: "/solid_errors"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", :as => :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", :as => :pwa_manifest

  # Defines the root path route ("/")
  root "start_page#index", as: :start

  namespace :oauth do
    get "/login", to: "sessions#login", as: "login"
    get "/callback", to: "sessions#callback"
  end

  namespace :party_data do
    scope "/:code" do
      scope "/settings" do
        get "/device_list", to: "settings#device_list", as: "party_device_list"
        post "/party_device", to: "settings#party_device", as: "set_party_device"
      end
      scope "/queue" do
        post "/add", to: "queues#add_song_to_queue", as: "add_to_queue"
      end
      get "/search", to: "search#search", as: "search"
    end
  end

  scope "/party" do
    post "/start/:code", to: "parties#start", as: "start_party"
    post "/stop/:code", to: "parties#stop", as: "stop_party"
    post "/skip/:code", to: "parties#skip", as: "skip_party"
    post "/resume/:code", to: "parties#resume", as: "resume_party"
    get "/:code/select_device", to: "parties#select_device", as: "select_device"
    get "/settings/:code", to: "parties#settings", as: "party_settings"
    get "/join/:code", to: "parties#join", as: "join_party"
    post "/create", to: "parties#create", as: "create_party"
    post "/:code/end", to: "parties#end", as: "end_party"
    get "/list", to: "parties#index", as: "party_list"
    get "/:code", to: "parties#show", as: "show_party"
  end
  
  scope '/accounts' do
    get '', to: "accounts#index", as: "account_settings"
    post '/destroy', to: "accounts#destroy", as: "account_destroy"
    post '/logout', to: "accounts#logout", as: "logout"
  end
  
  get '/terms_and_conditions', to: "legal#terms_and_conditions", as: "terms_and_conditions"
  get '/privacy_policy', to: "legal#privacy_policy", as: "privacy_policy"
  get '/cookie_policy', to: "legal#cookie_policy", as: "cookie_policy"
  resources :temporal_sessions, only: [ :create, :destroy ]

  get "/home", to: "home#index"

  match "*unmatched", to: "application#not_found_method", via: :all
end

app/views/layouts/_flash_messages.html.erb
<div data-controller="flash" class="flex flex-col justify-center items-center gap-2 fixed top-10 left-1/2 z-50">
  <% flash.each do |type, msg| %>
    <% color = type == "error" ?  "bg-red-700" : "bg-spotify-green"%>
    <% sign = type == "error" ?  "⚠" : "✓"%>
    <div data-flash-target="flash" class="opacity-0 <%= color %> w-auto max-w-72 md:max-w-xl transform -translate-x-1/2 text-gray-200 rounded-lg px-4 py-2 transition-opacity duration-300 ease-in-out">
      <p class="font-normal text-sm md:text-lg"><%= sign + " " + msg %></p>
    </div>
  <% end %>
</div>

app/views/layouts/_footer_nav.html.erb
<nav class="sticky bottom-0 flex justify-around items-center h-14 px-6 py-3 bg-black">
    <%= link_to start_path do %>
        <p class="text-base font-bold">FiestUp</p>
    <% end %>

    <%= link_to home_path do %>
        <%= image_tag 'home-icon.svg', class: 'w-9 h-9' %>
    <% end %>

    <%= link_to party_list_path do %>
        <%= image_tag 'party-list-icon.svg', class: 'w-9 h-9' %>
    <% end %>

    <%= link_to account_settings_path do %>
        <%= image_tag 'user-settings-icon.svg', class: 'w-9 h-9' %>
    <% end %>
</nav>

app/views/layouts/_header.html.erb
<div class="sticky top-0 z-10 bg-black">
    <nav class="flex justify-between items-center h-20 p-4">
        <div class="flex items-center gap-1 relative">
          <%= image_tag 'logo.png', class: 'w-5 h-8' %>
          <div class="relative">
            <p class="text-xl font-bold">FiestUp</p>
            <span class="absolute bottom-0 right-0 transform translate-x-2 translate-y-3 text-xs font-semibold bg-spotify-green px-1 py-0.2 rounded">BETA</span>
          </div>
        </div>


        <% if current_user %>
            <%= link_to account_settings_path, class: "flex justify-end gap-2 items-center w-full max-w-xs md:max-w-sm lg:max-w-md" do %>
            <%= image_tag current_user.image || 'user-settings-icon.svg', class: "object-cover h-10 w-10 rounded-full", alt: "User Profile Image" %>

            <span class="text-md max-w-36 md:max-w-fit md:text-lg lg:text-xl font-bold truncate" title="<%= current_user.username %>">
                <%= current_user.username %>
            </span>
            <% end %>
        <% end %>
    </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "FiestUp" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <%= render 'layouts/flash_messages' %>

      <div class="bg-black text-gray-200 h-[100vh]">
          <div class="lg:mx-32">
            <%= render 'layouts/header', locals: { user: current_user } %>
            <div class="flex flex-col gap-3 mx-1">
                <div class="flex gap-3">
                    <main class="flex-grow w-5/6 sticky top-20 h-[calc(100vh-136px)] p-2 rounded-2xl bg-spotify-gray-dark">
                        <%= yield %>
                    </main>
                </div>
            </div>
            <%= render 'layouts/footer_nav' %>
          </div>
      </div>
  </body>
</html>

app/views/layouts/start_page.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "FiestUp" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="relative min-h-screen bg-black flex flex-col">
    <div class="absolute inset-0 bg-gradient-to-br from-spotify-green via-spotify-green-complement to-purple-700 opacity-25"></div>
    <div class="relative flex flex-col flex-grow">
        <%= render 'layouts/flash_messages' %>

        <main class="flex-grow flex items-center justify-center">
            <%= yield %>
        </main>
    </div>

    <footer class="fixed bottom-0 w-full bg-spotify-gray-dark py-4">
        <div class="text-center text-gray-200">
            <p>Created by <a href="https://www.linkedin.com/in/hugo-garcia-calvo/" class="font-bold underline">Hugo Garcia</a></p>
        </div>
    </footer>
  </body>
</html>